# Generated by Django 4.0.5 on 2022-07-05 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_product_balance_alter_product_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bakery', 'выпечка'), ('sweets', 'сладости'), ('drinks', 'напитки'), ('veggies', 'овощи'), ('other', 'разное')], default='bakery', max_length=20, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='p_name',
            field=models.CharField(default='No Product', max_length=100, verbose_name='Имя товара'),
        ),
    ]
