# Generated by Django 4.0.5 on 2022-07-05 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_product_category_alter_product_p_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('bakery', 'выпечка'), ('sweets', 'сладости'), ('drinks', 'напитки'), ('veggies', 'овощи'), ('other', 'разное')], default='сладости', max_length=20, verbose_name='Категория'),
        ),
    ]
