# Generated by Django 4.0.5 on 2022-08-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_order_alter_product_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('product_create', 'Добавление товара'), ('product_update', 'Редактирование товара'), ('product_delete', 'Удаление товара')], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
